Update ami.yml (#79)

diff --git a/.github/workflows/ami.yml b/.github/workflows/ami.yml
--- a/.github/workflows/ami.yml
+++ b/.github/workflows/ami.yml
@@ -29,23 +29,58 @@ jobs:
          packer plugins install github.com/hashicorp/amazon
         if: always()
       
-      - name: Run Packer
+      - name: Building Packer Template
         run: |
-          # Install Packer
-          curl -fsSL https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip -o packer.zip
-          unzip packer.zip
-          sudo mv packer /usr/local/bin/
-          packer init debian-ami.pkr.hcl
-
-          # Run Packer build (modify this command as needed)
           packer build -var "demo_account_id=${{ secrets.DEMO_ACCOUNT_ID }}" \
-                     -var "source_ami=${{ secrets.SOURCE_AMI }}" \
-                     -var "ami_name=${{ secrets.AMI_NAME }}" \
-                     -var "aws_region=${{ secrets.AWS_REGION }}" \
-                     -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY}}" \
-                     -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY}}" \
-                      debian-ami.pkr.hcl
-                      
+                       -var "source_ami=${{ secrets.SOURCE_AMI }}" \
+                       -var "aws_region=${{ secrets.AWS_REGION }}" \
+                       -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
+                       -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
+                       debian-ami.pkr.hcl | sudo tee output.txt
+          tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }' >> ami.txt
 
-      
+      - name: Create new launch template version
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
+        run: |
+          AMI_ID=$(cat ami.txt)
+          LAUNCH_TEMPLATE_NAME=$(aws ec2 describe-launch-templates --query 'LaunchTemplates[?starts_with(LaunchTemplateName, launchTemplate) == true].LaunchTemplateName' --output text)
+          aws ec2 create-launch-template-version --launch-template-name $LAUNCH_TEMPLATE_NAME --version-description latest --source-version 1 --launch-template-data "ImageId=$AMI_ID"
 
+      - name: Update the autoscaling group
+        id: set_asg_name
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
+        run: |
+          AUTO_SCALING_GROUP_NAME=$(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[?starts_with(AutoScalingGroupName, 'autoScalingGroup-')].AutoScalingGroupName" --output text | head -n 1)
+          if [ -z "$AUTO_SCALING_GROUP_NAME" ]; then
+              echo "No Auto Scaling Group found with the specified prefix."
+              exit 1
+          fi
+          echo "Auto Scaling Group Name: $AUTO_SCALING_GROUP_NAME"
+          echo "AUTO_SCALING_GROUP_NAME=$AUTO_SCALING_GROUP_NAME" >> $GITHUB_ENV
+          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $AUTO_SCALING_GROUP_NAME --launch-template LaunchTemplateName=launchTemplate-941aa22,Version='$Latest'
+
+      - name: Instance refresh and wait
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.DEMO_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEMO_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
+        run: |
+          REFRESH_ID=$(aws autoscaling start-instance-refresh --auto-scaling-group-name "$AUTO_SCALING_GROUP_NAME" --query 'InstanceRefreshId' --output text)
+          STATUS="pending"
+          while [ "$STATUS" != "Successful" ]; do
+            echo "Waiting for instance refresh to complete..."
+            sleep 60 
+            STATUS=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name "$AUTO_SCALING_GROUP_NAME" --instance-refresh-ids $REFRESH_ID --query 'InstanceRefreshes[0].Status' --output text)
+            if [ "$STATUS" == "Failed" ]; then
+              echo "Instance refresh failed."
+              exit 1
+            fi
+          done
+          echo "Instance refresh completed successfully."
+     
